# Generated by Django 4.2.5 on 2023-11-15 05:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoCultural',
            fields=[
                ('idDestino', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagenes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additionalInfo', models.TextField()),
                ('imageURL', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('detailsPageURL', models.URLField()),
                ('liveURL', models.URLField()),
                ('geometria', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAdicional',
            fields=[
                ('idRecurso', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('enlace', models.CharField(max_length=255)),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destinocultural')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaInteractiva',
            fields=[
                ('idPregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('opciones', models.CharField(max_length=255)),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destinocultural')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVisitas',
            fields=[
                ('idHistorial', models.IntegerField(primary_key=True, serialize=False)),
                ('destinoVisitados', models.CharField(max_length=255)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destinocultural')),
            ],
        ),
        migrations.AddField(
            model_name='destinocultural',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.IntegerField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destinocultural')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idCalificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.destinocultural')),
            ],
        ),
    ]
